name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  MIX_ENV: test
jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.9', '1.10', '1.11', '1.12', '1.13', '1.14']
        otp: ['20.3', '21.3', '22.3', '23.3', '24.3', '25.1']
        exclude:
          - elixir: '1.14'
            otp: '22.3'
          - elixir: '1.14'
            otp: '21.3'
          - elixir: '1.14'
            otp: '20.3'
          - elixir: '1.13'
            otp: '21.3'
          - elixir: '1.13'
            otp: '20.3'
          - elixir: '1.12'
            otp: '25.1'
          - elixir: '1.12'
            otp: '21.3'
          - elixir: '1.12'
            otp: '20.3'
          - elixir: '1.11'
            otp: '25.1'
          - elixir: '1.11'
            otp: '20.3'
          - elixir: '1.10'
            otp: '25.1'
          - elixir: '1.10'
            otp: '24.3'
          - elixir: '1.10'
            otp: '20.3'
          - elixir: '1.9'
            otp: '25.1'
          - elixir: '1.9'
            otp: '24.3'
          - elixir: '1.9'
            otp: '23.3'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix dialyzer --plt

  static_code_analysis:
    name: Static Code Analysis
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14']
        otp: ['25.1']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

      - name: Run Dialyzer
        run: mix dialyzer --no-check --halt-exit-status

  unit_tests:
    name: Unit Tests
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: ['1.9', '1.10', '1.11', '1.12', '1.13', '1.14']
        otp: ['20.3', '21.3', '22.3', '23.3', '24.3', '25.1']
        exclude:
          - elixir: '1.14'
            otp: '22.3'
          - elixir: '1.14'
            otp: '21.3'
          - elixir: '1.14'
            otp: '20.3'
          - elixir: '1.13'
            otp: '21.3'
          - elixir: '1.13'
            otp: '20.3'
          - elixir: '1.12'
            otp: '25.1'
          - elixir: '1.12'
            otp: '21.3'
          - elixir: '1.12'
            otp: '20.3'
          - elixir: '1.11'
            otp: '25.1'
          - elixir: '1.11'
            otp: '20.3'
          - elixir: '1.10'
            otp: '25.1'
          - elixir: '1.10'
            otp: '24.3'
          - elixir: '1.10'
            otp: '20.3'
          - elixir: '1.9'
            otp: '25.1'
          - elixir: '1.9'
            otp: '24.3'
          - elixir: '1.9'
            otp: '23.3'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Run Test
        run: mix test --cover --trace --slowest 10
